dist: trusty
sudo: false
language: python
python:
    # FontForge uses Python 2, so there is no point to testing Python 3.
    - "2.7"
virtualenv:
    # fontforge is installed in the global site-packages directory.
    system_site_packages: true
addons:
    apt:
        sources:
            - sourceline: ppa:fontforge/fontforge
        packages:
            - python-fontforge=20170730-0ubuntu1~trusty
install:
    # libharfbuzz-bin is too out of date to use.
    - HB_VERSION=1.8.1
    - curl -O https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-$HB_VERSION.tar.bz2
    - tar -xjf harfbuzz-$HB_VERSION.tar.bz2
    - pushd harfbuzz-$HB_VERSION
    - ./configure
    - cd src
    - make
    - cd ../util
    - make
    - export PATH="$PWD:$PATH"
    - popd
script: make check
