dist: trusty
language: python
python:
    # FontForge uses Python 2, so there is no point to testing Python 3.
    - "2.7"
virtualenv:
    # fontforge is installed in the global site-packages directory.
    system_site_packages: true
env:
    global:
        - HB_VERSION=2.3.1
    matrix:
        - OLD_REQUIREMENTS=false
        - OLD_REQUIREMENTS=true
cache:
    directories:
        - .hb
addons:
    apt:
        sources:
            - sourceline: ppa:fontforge/fontforge
        packages:
            - python-fontforge=20170730-0ubuntu1~trusty
before_install:
    -
        if [ "$OLD_REQUIREMENTS" = true ];
        then
            pip install packaging;
            ./get-old-requirements.py --input requirements-to-freeze.txt --output requirements.txt;
        fi
install:
    - pip install -r requirements.txt
    # libharfbuzz-bin is too out of date to use.
    - make HB_VERSION=$HB_VERSION hb-shape
    - export PATH="$PWD/.hb/harfbuzz-$HB_VERSION/util:$PATH"
script: make check
