# Copyright 2018-2019 David Corbett
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

dist: bionic
services:
    - xvfb
language: python
python:
    - "3.7"
env:
    global:
        - FF_VERSION=20190801
        - HB_VERSION=2.5.2
    matrix:
        - REQUIREMENTS=frozen
        - REQUIREMENTS=oldest
        - REQUIREMENTS=newest
cache:
    directories:
        - .ff
        - .hb
    pip: true
before_install:
    # No APT package exists for a recent FontForge with Python 3.7 support.
    - mkdir -p .ff/fontforge-$FF_VERSION
    - pushd .ff/fontforge-$FF_VERSION
    - |
        if [ ! -f fontforge ]
        then
            curl -Lo fontforge "$(
                curl "$(
                    curl https://api.github.com/repos/fontforge/fontforge/releases \
                    | jq -r ".[] | select(.tag_name == \"$FF_VERSION\").assets_url"
                )" \
                | jq -r '.[] | select(.name | endswith(".AppImage")).browser_download_url'
            )"
            chmod +x fontforge
        fi
    - export PATH="$PWD:$PATH"
    - export PYTHONHOME="$(python3 -c 'import sys; print(sys.prefix)')"
    - popd

    # libharfbuzz-bin is too out of date to use.
    - make HB_VERSION=$HB_VERSION hb-shape
    - export PATH="$PWD/.hb/harfbuzz-$HB_VERSION/util:$PATH"

    - |
        if [ "$REQUIREMENTS" = oldest ]
        then
            pip install packaging
            ./get-old-requirements.py --input requirements-to-freeze.txt --output requirements.txt
        fi
    - |
        if [ "$REQUIREMENTS" = newest ]
        then
            cp requirements-to-freeze.txt requirements.txt
        fi
script: xvfb-run -a make check
